services:
  # Motor de Streaming (Stremio Service Oficial)
  stremio-runtime:
    image: stremio/server:latest
    container_name: stremio-server
    restart: unless-stopped
    # Acceso a la GPU integrada para Transcodificación por hardware
    device_cgroup_rules:
      - 'c 226:* rmw'
    devices:
      - /dev/dri:/dev/dri 
    ports:
      - "11470:11470"
    volumes:
      - ./stremio-data:/root/.stremio-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  # Interfaz Web (Estilo Netflix Oficial)
  stremio-web:
    image: stremio/stremio-web:latest
    container_name: stremio-web
    restart: unless-stopped
    ports:
      - "8081:80" # Web UI en el puerto 8081
    depends_on:
      - stremio-runtime
