services:
  # Stremio (Motor de Streaming + Interfaz Web Integrada)
  stremio:
    image: tsaridas/stremio-docker:latest
    container_name: stremio
    restart: unless-stopped
    # Acceso a la GPU integrada (QuickSync del i5-8400T)
    device_cgroup_rules:
      - 'c 226:* rmw'
    devices:
      - /dev/dri:/dev/dri 
    ports:
      - "8080:8080" # Web UI y Streaming Server
    volumes:
      - ./stremio-data:/root/.stremio-server
    environment:
      - NO_CORS=1
      - AUTO_SERVER_URL=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
